[package]
name = "ancorix_winit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Feeds winit events into Ancorix input."
license.workspace = true
repository.workspace = true

[dependencies]
ancorix_input = { workspace = true }
winit = { workspace = true }
