[package]
name = "ancorix_window"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Creates the window and runs the frame loop for Ancorix."
license.workspace = true
repository.workspace = true

[features]
unstable_shaders = ["dep:ancorix_shader", "ancorix_ctx/unstable_shaders", "ancorix_render/unstable_shaders"]

[dependencies]
ancorix_asset = { workspace = true }
ancorix_color = { workspace = true }
ancorix_ctx = { workspace = true }
ancorix_input = { workspace = true }
ancorix_winit = { workspace = true }
ancorix_build = { workspace = true }
ancorix_axb = { workspace = true }
ancorix_ash = { workspace = true }
ancorix_draw = { workspace = true }
ancorix_math = { workspace = true }
ancorix_render = { workspace = true }
ancorix_shader = { workspace = true, optional = true }
ash = { workspace = true }
winit = { workspace = true }
serde_json = { workspace = true }
raw-window-handle = { workspace = true }
